sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project fib-k8s-378320
  - gcloud config set compute/zone me-west1-a
  - gcloud container clusters get-credentials fib-k8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t talhenti/fib-client-test -f ./client/Dockerfile.dev ./client
  - docker build -t talhenti/fib-server-test -f ./server/Dockerfile.dev ./server
  - docker build -t talhenti/fib-worker-test -f ./worker/Dockerfile.dev ./worker

script:
  - docker run -e CI=true talhenti/fib-client-test npm run test
  - docker run -e CI=true talhenti/fib-server-test npm run test
  - docker run -e CI=true talhenti/fib-worker-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master